title: "Moe"
description: "Showcasing my projects, contributions, and certifications."
theme: hacker
url: "https://github.com/M-code-42/Pr0jects-Certs"  # Replace with your repository's GitHub Pages URL
baseurl: ""  # Leave empty unless the site is being served from a subdirectory
markdown: kramdown
paginate: 5

# Navigation links for easy access
navigation:
  - title: "Home"
    url: "/"
  - title: "Projects & Contributions"
    url: "/projects/"
  - title: "Professional Certificates"
    url: "/certifications/"

plugins:
  - jekyll-feed
